defmodule BookReviewsWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :book_reviews

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_book_reviews_key",
    signing_salt: "jWvnOXKq",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  #
  # Both mounts are wrapped in `BookReviewsWeb.Static` so the decision of who
  # serves static assets (this app, or a reverse proxy at the edge) can be
  # made at runtime via `:serve_static` (`SERVE_STATIC_ASSETS` env var).
  plug BookReviewsWeb.Static,
    at: "/",
    from: :book_reviews,
    gzip: not code_reloading?,
    only: BookReviewsWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # User uploads (book covers / author photos). The directory is configurable:
  # without a proxy it lives under priv/static/uploads inside this release;
  # with a proxy it is a shared volume that the edge serves directly.
  plug BookReviewsWeb.Static,
    at: "/uploads",
    uploads: true,
    gzip: false,
    raise_on_missing_only: false

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug BookReviewsWeb.Router
end
